# Globally define build args for all stages
ARG TARGETOS
ARG TARGETARCH

# --- Stage 1: Build the React Frontend ---
# Use the native build platform to avoid QEMU emulation overhead for frontend
FROM --platform=$BUILDPLATFORM node:20-alpine AS frontend-builder
WORKDIR /app
# Note the paths relative to the root context
COPY frontend/package*.json ./
RUN npm ci --legacy-peer-deps
COPY frontend/ ./
RUN npm run build

# --- Stage 2: Build the Go Backend ---
# Use native build platform for compilation speed, then cross-compile
FROM --platform=$BUILDPLATFORM golang:1.24-alpine AS backend-builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache git

# Copy module files first (from the backend directory)
COPY backend/go.mod backend/go.sum ./
RUN go mod download

# Copy the entire backend source code
COPY backend/ ./

# Install swag CLI to generate documentation if needed
RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN /go/bin/swag init

# Cross-compile the binary for the SPECIFIC target architecture
# Using TARGETARCH ensures the binary matches the server (AMD64 or ARM64)
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-amd64} \
    go build -ldflags="-s -w" -v -o /app/helm-analytics .

# --- Stage 3: Create the Final Production Image ---
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app

# Copy built frontend assets
COPY --from=frontend-builder /app/dist ./static

# Copy compiled backend binary
COPY --from=backend-builder /app/helm-analytics .

# Copy documentation generated by swag
COPY --from=backend-builder /app/docs ./docs

# Copy GeoIP databases from the backend directory source
COPY backend/GeoLite2-Country.mmdb .
COPY backend/GeoLite2-ASN.mmdb .

# Ensure the binary is executable
RUN chmod +x ./helm-analytics

ENV PORT=8012
EXPOSE 8012

# Entry point for the application
ENTRYPOINT ["./helm-analytics"]